name: Node.js CI - with cache

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Build Node
      uses: JediSchools/GHA.Jedi.Templates/.github/actions/build-node@main
